name: Test-GG
staging: true
team: dmp
domain: example
whitesourceEnabled: true
kubescoreEnabled: false
cdEnabled: false
services:
- name: neat-service
  type: http-grpc
  ciEnabled: true
argoAppNamesProduction: ""
argoAppNamesStaging: ""
deploy:
  platform: ""
  product: ""
