openapi: 3.0.1
info:
  title: gogen
  description: Monorepo and service generator for Golang projects.
  x-cortex-tag: adsstaff_gogen
  x-cortex-type: service
  x-cortex-groups:
  - ads-se
  x-cortex-domain-parents:
  - tag: adsstaff
  x-cortex-git:
    gitlab:
      repository: ads/adsstaff/gogen
  x-cortex-owners:
  - type: group
    name: team-adsstaff
    provider: CORTEX
    description: Part of ads-se squad.
  x-cortex-issues:
    jira:
      defaultJql: ""
