{{`{{- if .Values.`}}{{ .ServiceNameUnderscore }}{{`.enabled }}`}}
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: {{`{{ .Release.Name }}`}}-{{ .ServiceName }}
    env: {{`{{ .Values.env }}`}}
    release: {{`{{ .Release.Name }}`}}
    domain: {{`{{ required "A domain value is required" .Values.domain }}`}}
    team: {{`{{ required "A team value is required" .Values.team }}`}}
    app.kubernetes.io/name: {{`{{ .Release.Name }}`}}-{{ .ServiceName }}
    app.kubernetes.io/instance: {{`{{ $.Release.Name }}`}}
    app.kubernetes.io/managed-by: {{`{{ $.Release.Service }}`}}
    helm.sh/chart: {{`{{ include "this.chart" . }}`}}
  name: {{`{{ .Release.Name }}`}}-{{ .ServiceName }}
  namespace: {{`{{ .Release.Namespace }}`}}
spec:
  suspend: {{`{{ .Values.`}}{{ .ServiceNameUnderscore }}{{`.suspend }}`}}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  schedule: "{{`{{ .Values.`}}{{ .ServiceNameUnderscore }}{{`.schedule }}`}}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{`{{ .Release.Name }}`}}-{{ .ServiceName }}
            env: {{`{{ .Values.env }}`}}
            release: {{`{{ .Release.Name }}`}}
            domain: {{`{{ required "A domain value is required" .Values.domain }}`}}
            team: {{`{{ required "A team value is required" .Values.team }}`}}
            app.kubernetes.io/name: {{`{{ .Release.Name }}`}}-{{ .ServiceName }}
            app.kubernetes.io/instance: {{`{{ $.Release.Name }}`}}
            app.kubernetes.io/managed-by: {{`{{ $.Release.Service }}`}}
            helm.sh/chart: {{`{{ include "this.chart" . }}`}}
        spec:
          serviceAccountName: {{`{{ .Values.`}}{{ .ServiceNameUnderscore }}{{`.serviceAccount }}`}}
          containers:
            - name: {{`{{ .Release.Name }}`}}-{{ .ServiceName }}
              image: {{`{{ .Values.`}}{{ .ServiceNameUnderscore }}{{`.docker.image }}`}}:{{`{{ .Values.`}}{{ .ServiceNameUnderscore }}{{`.docker.tag }}`}}
              env:
                - name: ENV
                  value: {{`{{ .Values.env }}`}}
                - name: GCP_PROJECT
                  value: {{`{{ .Values.gcpProject }}`}}
                - name: INPLAY
                  value: {{ .ServiceInplay }}
          restartPolicy: Never
          terminationGracePeriodSeconds: 300
{{`{{- end -}}`}}