{{`{{- if .Values.`}}{{ .ServiceNameUnderscore }}{{`.hpa.enabled }}`}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{`{{ .Release.Name }}`}}-{{ .ServiceName }}
  labels:
    app: {{`{{ .Release.Name }}`}}-{{ .ServiceName }}
    app.kubernetes.io/name: {{`{{ .Release.Name }}`}}-{{ .ServiceName }}
    app.kubernetes.io/instance: {{`{{ $.Release.Name }}`}}
    app.kubernetes.io/managed-by: {{`{{ $.Release.Service }}`}}
    helm.sh/chart: {{`{{ include "this.chart" . }}`}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{`{{ .Release.Name }}`}}-{{ .ServiceName }}
  minReplicas: {{`{{ .Values.`}}{{ .ServiceNameUnderscore }}{{`.minReplicas }}`}}
  maxReplicas: {{`{{ .Values.`}}{{ .ServiceNameUnderscore }}{{`.maxReplicas }}`}}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 200
        periodSeconds: 10
      - type: Pods
        value: 10
        periodSeconds: 10
      selectPolicy: Max
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        averageUtilization:  {{`{{ required "A target CPU value is required for HPA" .Values.`}}{{ .ServiceNameUnderscore }}.hpa.targetMemory }}
        type: Utilization
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization:  {{`{{ required "A target CPU value is required for HPA" .Values.`}}{{ .ServiceNameUnderscore }}.hpa.targetCPU }}
        type: Utilization
{{`{{- end -}}`}}