{{`{{- if .Values.`}}{{ .ServiceNameUnderscore }}{{`.hpa.enabled }}`}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{`{{ .Release.Name }}`}}-{{ .ServiceName }}
  labels:
    app: {{`{{ .Release.Name }}`}}-{{ .ServiceName }}
    app.kubernetes.io/name: {{`{{ .Release.Name }}`}}-{{ .ServiceName }}
    app.kubernetes.io/instance: {{`{{ $.Release.Name }}`}}
    app.kubernetes.io/managed-by: {{`{{ $.Release.Service }}`}}
    helm.sh/chart: {{`{{ include "this.chart" . }}`}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{`{{ .Release.Name }}`}}-{{ .ServiceName }}
  minReplicas: {{`{{ .Values.`}}{{ .ServiceNameUnderscore }}{{`.minReplicas }}`}}
  maxReplicas: {{`{{ .Values.`}}{{ .ServiceNameUnderscore }}{{`.maxReplicas }}`}}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{`{{ required "A target CPU value is required for HPA" .Values.`}}{{ .ServiceNameUnderscore }}.hpa.targetCPU }}
{{`{{- end -}}`}}